const KEY="plemate_v8";
const stageImages=["evolution_1.png","evolution_2.png","evolution_3.png","evolution_4.png","evolution_5.png"];
const stageNames=["Newborn","Curious","Radiant","Wise","Celestial"];
const stageCare=[
  {dirty:"Very tired & dusty",clean:"Bright-eyed Newborn"},
  {dirty:"Sleepy & scruffy",clean:"Fresh Curious"},
  {dirty:"Tired but determined",clean:"Radiant & happy"},
  {dirty:"A little weary",clean:"Wise & glowing"},
  {dirty:"Resting after a long quest",clean:"Celestial & joyful"}
];
const thoughts=["Discipline today is freedom tomorrow. ♡","One hard topic at a time. We can do this.","Your future self will thank you for showing up today.","Small, consistent steps create extraordinary endings.","Take the next small step, future MD. ✨","Progress is allowed to be slow. Keep moving.","Hikari believes in you. Now let's make today's plan."];
const gifts=[["🧪","Focus Elixir","A tiny boost for your next study session."],["🍀","Lucky Leaf","A reminder that you are already moving forward."],["📚","Study Scroll","One more page becomes one more thing you know."],["💎","Clarity Crystal","For a calm reset before your next study block."],["🪶","Lucky Feather","Light steps, steady pace, strong finish."],["🌙","Moon Charm","A little luck for tonight's review."]];
const tips=["Take 5 slow breaths before starting a difficult block.","Hydrate before your next study session.","Stretch for 3–5 minutes after a long topic.","A short walk can be a useful reset.","Put the phone out of reach for one focused block.","Write tomorrow's three most important tasks before bed."];
const subjectIcons={Pathology:"🧫",Pharmacology:"💊",Physiology:"🧬",'Internal Medicine':"🩺",Surgery:"🔪",OBGyn:"🌸",Biochemistry:"🧪",Microbiology:"🦠",Anatomy:"🦴",'Preventive Medicine':"🛡️", 'Legal Medicine':"⚖️", Pediatrics:"🧸"};
const subjectsSeed=[
{name:"Pathology",color:"#e85c64",performance:22,hours:0,studied:0,difficulty:null,focus:"Target weak pathology patterns, mechanisms, and practice-test rationales.",overview:"Very low baseline performance; needs active recall and practice.",deadline:""},
{name:"Pharmacology",color:"#e6ac2f",performance:24,hours:0,studied:0,difficulty:null,focus:"Drug classes, mechanisms, adverse effects, and clinical application.",overview:"Very low baseline performance.",deadline:""},
{name:"Physiology",color:"#8a5fbe",performance:26,hours:27.3653,studied:0,difficulty:9,focus:"Prioritize cardiovascular, respiratory, renal and high-yield analysis questions.",overview:"Difficulty 9/10; cross-over, formulas, computations and relationship questions are emphasized.",deadline:"2026-08-20T23:59",handout:112,lecture:27*3600+21*60+55},
{name:"Internal Medicine",color:"#4b8bd4",performance:30,hours:0,studied:0,difficulty:null,focus:"Case recognition, diagnostic reasoning, and practice rationales.",overview:"Low baseline performance.",deadline:""},
{name:"Surgery",color:"#a970c5",performance:31,hours:24,studied:0,difficulty:8,focus:"Case-based application; Whiteboards; Pearls A/B; practice tests.",overview:"Difficulty 8/10; increasingly clinical and case-based.",deadline:"",handout:131,lecture:24*3600},
{name:"OBGyn",color:"#e78aa9",performance:40,hours:0,studied:0,difficulty:null,focus:"High-yield algorithms, clinical patterns, practice questions.",overview:"Mid-range baseline.",deadline:""},
{name:"Biochemistry",color:"#62ba84",performance:40,hours:22,studied:0,difficulty:4,focus:"Clinical conditions and physio-biochem correlations; lectures with handout.",overview:"Difficulty 4/10 and relatively stable/fair.",deadline:"",handout:105,lecture:22*3600},
{name:"Microbiology",color:"#e8a32f",performance:47,hours:17.3136,studied:0,difficulty:5,focus:"Master bacteria, viruses, parasites, entomology and mycology; use Handout + Supertable + PTs.",overview:"Difficulty 5/10; cross-over with IM, PrevMed and Pharma.",deadline:"",handout:81,supertable:32,lecture:17*3600+18*60+49},
{name:"Anatomy",color:"#3e8ad8",performance:44,hours:0,studied:0,difficulty:null,focus:"Target weak anatomical regions and clinical correlations.",overview:"Moderate baseline performance.",deadline:""},
{name:"Preventive Medicine",color:"#67a84c",performance:49,hours:0,studied:0,difficulty:null,focus:"High-yield public health concepts and applied questions.",overview:"Near-midline baseline.",deadline:""},
{name:"Legal Medicine",color:"#c58a51",performance:51.5,hours:8.9667,studied:0,difficulty:4,focus:"Master the handout and 300-item Supersamplex; aim high.",overview:"Difficulty 4/10 with a restricted source base but law-application cases.",deadline:"",handout:83,supersamplex:300,lecture:8*3600+58*60},
{name:"Pediatrics",color:"#6d79a8",performance:61,hours:17.1333,studied:0,difficulty:6,focus:"Maintain, consolidate high-yield concepts, and use PTs to identify gaps.",overview:"Strongest baseline; fair but not a giveaway; cross-over with Micro, Biochem and Nutrition.",deadline:"",handout:111,lecture:17*3600+8*60}];
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x)return x}catch{}return{pleDate:"2026-10-11T17:00",calendarUrl:"https://calendar.google.com/calendar/embed?src=1657328d71fa231c834764e107b84d3b32369e09f90a603efa6b1a7541f7cb4f%40group.calendar.google.com&ctz=Asia%2FManila",subjects:structuredClone(subjectsSeed),chat:[{r:"bot",t:"Hi Marianne! I’m Hikari’s study companion. How can I help you today? ♡"}],memory:[],calendar:[],board:[],pet:{xp:0,energy:100,coins:0,gems:0,rewardHours:0,lastProgress:0,lastDay:"",cleanliness:20,mood:25,careMessage:"Hikari starts each day a little sleepy and dusty. ✨"}}}
let state=load(),page="dashboard";let pomo={sec:1500,total:1500,timer:null,length:25};
function save(){localStorage.setItem(KEY,JSON.stringify(state))} function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}function hrs(h){let s=Math.max(0,Math.round((+h||0)*3600)),H=Math.floor(s/3600),M=Math.floor(s%3600/60),S=s%60;return `${H}h ${String(M).padStart(2,"0")}m ${String(S).padStart(2,"0")}s`}function totalStudied(){return state.subjects.reduce((a,s)=>a+(+s.studied||0),0)}function totalRequired(){return state.subjects.reduce((a,s)=>a+(+s.hours||0),0)}function progressPct(){const r=totalRequired();return r?Math.min(100,totalStudied()/r*100):0}
function startOfDay(){const d=new Date().toISOString().slice(0,10);if(state.pet.lastDay!==d){state.pet.lastDay=d;state.pet.cleanliness=20;state.pet.mood=25;state.pet.careMessage="New day! Hikari looks a little tired and dusty. Give her some care today. ✨";save()}}
function updateProgressRewards(){const p=progressPct();const delta=Math.max(0,p-(state.pet.lastProgress||0));if(delta>=1){const whole=Math.floor(delta);state.pet.xp+=whole*40;state.pet.coins+=whole*20;state.pet.energy=Math.min(100,state.pet.energy+whole*3);state.pet.lastProgress=p;while(state.pet.xp>=500){state.pet.xp-=500;state.pet.gems+=1;state.pet.mood=Math.min(100,state.pet.mood+5)}}const wholeHours=Math.floor(totalStudied());if(wholeHours>state.pet.rewardHours){const n=wholeHours-state.pet.rewardHours;state.pet.rewardHours=wholeHours;state.pet.coins+=n*50;state.pet.energy=Math.min(100,state.pet.energy+n*10)}save()}
function stage(){const p=progressPct();return p>=90?4:p>=70?3:p>=40?2:p>=15?1:0}
function visualState(){return Math.min(100,Math.max(0,state.pet.cleanliness))}
function nav(){document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===page))}
document.getElementById("nav").onclick=e=>{const b=e.target.closest("button[data-page]");if(b){page=b.dataset.page;nav();render()}};document.getElementById("app").addEventListener("click",e=>{const go=e.target.closest("[data-go]"),care=e.target.closest("[data-care]"),chat=e.target.closest("[data-chat]");if(go){page=go.dataset.go;nav();render()}if(care)doCare(care.dataset.care);if(chat)routeChat(chat.dataset.chat)});
function render(){startOfDay();updateProgressRewards();document.getElementById("app").innerHTML=document.getElementById(page).innerHTML;const f={dashboard,petPage,oplanPage,calendarPage,corkboardPage,subjectsPage,settingsPage}[page];f();}
function petImage(stageIndex,dirty){return stageImages[stageIndex]||stageImages[0]}
function applyPetVisual(img,dirty){img.classList.toggle("pet-dirty",dirty);img.classList.toggle("pet-clean",!dirty);img.style.filter=dirty?`saturate(.55) brightness(.72) sepia(.18)`:`saturate(1.08) brightness(1.05)`}
function dashboard(){renderPetMini();renderCountdown();renderSubjects();renderStudyGuide();renderFocus();renderPerformance();renderBars();renderChat();setupPomo();renderGift();renderWellness()}
function renderPetMini(){const st=stage(), dirty=visualState()<70;const img=document.getElementById("railPet");img.src=petImage(st,dirty);applyPetVisual(img,dirty);document.getElementById("railStage").textContent=`Level ${st+1} · ${stageNames[st]}`;document.getElementById("xpBar").style.width=(state.pet.xp/500*100)+"%";document.getElementById("energy").textContent=state.pet.energy;document.getElementById("coins").textContent=state.pet.coins;document.getElementById("gems").textContent=state.pet.gems;document.getElementById("petStateTag").textContent=dirty?stageCare[st].dirty:stageCare[st].clean;document.getElementById("careMessageMini").textContent=state.pet.careMessage}
function renderCountdown(){const d=new Date(state.pleDate)-new Date(),mins=Math.max(0,Math.floor(d/60000)),days=Math.floor(mins/1440),h=Math.floor(mins%1440/60),m=mins%60;document.getElementById("countdown").innerHTML=`${days} <span>DAYS</span> ${String(h).padStart(2,"0")} <span>HOURS</span> ${String(m).padStart(2,"0")} <span>MINUTES</span>`;document.getElementById("pleDateText").textContent=new Date(state.pleDate).toLocaleString([], {dateStyle:"long",timeStyle:"short"});document.getElementById("nowText").textContent="Today is "+new Date().toLocaleString([], {dateStyle:"long",timeStyle:"short"})}
function renderSubjects(){const a=state.subjects.map(s=>({...s,score:(100-(s.performance??50))+(s.deadline?Math.max(0,100/Math.max(.5,(new Date(s.deadline)-new Date())/86400000)):0)})).sort((a,b)=>b.score-a.score).slice(0,7);document.getElementById("studiedTotal").textContent=hrs(totalStudied());document.getElementById("remainingTotal").textContent=hrs(totalRequired()-totalStudied());document.getElementById("subjectRows").innerHTML=a.map(s=>{let p=s.hours?s.studied/s.hours*100:0;return `<div class="subject-row"><div class="subject-label"><span class="subject-icon">${subjectIcons[s.name]||"📘"}</span><b style="color:${s.color}">${esc(s.name)}</b></div><div class="bar"><div style="width:${Math.min(100,p)}%;background:${s.color}"></div></div><div>${Math.round(p)}%</div><div>${s.hours?hrs(s.studied):"—"}</div><div><b>${s.hours?hrs(s.hours-s.studied):"—"}</b><small>${s.deadline?"Due "+Math.ceil((new Date(s.deadline)-new Date())/86400000)+"d":""}</small></div></div>`}).join("")}
function getPicks(){return state.subjects.filter(s=>(s.hours||0)>s.studied).map(s=>({...s,score:(100-(s.performance??50))+(s.deadline?Math.max(0,100/Math.max(.5,(new Date(s.deadline)-new Date())/86400000)):0)})).sort((a,b)=>b.score-a.score).slice(0,5)}
function renderStudyGuide(){const p=getPicks().slice(0,4);document.getElementById("studyGuide").innerHTML=p.map((s,i)=>`<div class="study-item"><b>${i+1}.</b><span>${subjectIcons[s.name]||"📘"} ${esc(s.name)}</span><span class="tag">${s.performance<30?"High Yield":s.deadline?"Due Soon":"Priority"}</span></div>`).join("")||"<p class='muted'>Add workload/deadline data to create your study guide.</p>"}
function renderFocus(){const p=getPicks().slice(0,4);document.getElementById("focusMeta").textContent="No fixed times";document.getElementById("focus").innerHTML=p.map(s=>`<div class="focus-item"><span>${s.performance<30?"🔴":"🟡"}</span><b>${subjectIcons[s.name]||"📘"} ${esc(s.name)}</b><span>${s.hours?hrs(s.hours-s.studied):"Workload not set"}</span></div>`).join("")||"<p>No tasks yet.</p>"}
function renderPerformance(){const arr=state.subjects.filter(s=>s.performance!=null),avg=arr.reduce((a,s)=>a+s.performance,0)/Math.max(1,arr.length),weak=arr.filter(s=>s.performance<50).length;document.getElementById("performance").innerHTML=`<div class="perf-grid"><div><b>${avg.toFixed(1)}%</b><small>Average</small></div><div><b>${weak}</b><small>Need work</small></div><div><b>${arr.length-weak}</b><small>Moderate/strong</small></div></div>`}
function renderBars(){document.getElementById("bars").innerHTML=[5.3,6.75,4.25,7.5,6.17,8,2.5].map((v,i)=>`<div class="bar-day"><div class="bar-track"><div class="bar-fill" style="height:${v/8*100}%"></div></div><b>${v.toFixed(2)}h</b><small>${["Mon","Tue","Wed","Thu","Fri","Sat","Sun"][i]}</small></div>`).join("")}
function renderGift(){const i=Math.floor(Date.now()/86400000)%gifts.length;document.getElementById("giftIcon").textContent=gifts[i][0];document.getElementById("giftName").textContent=gifts[i][1];document.getElementById("giftDesc").textContent=gifts[i][2]}
function renderWellness(){document.getElementById("wellness").textContent=tips[new Date().getDate()%tips.length]}
function renderChat(){const log=document.getElementById("chatLog");log.innerHTML=state.chat.map(m=>`<div class="chat-msg ${m.r}">${esc(m.t)}</div>`).join("");log.scrollTop=log.scrollHeight;document.getElementById("chatForm").onsubmit=e=>{e.preventDefault();const i=document.getElementById("chatInput"),t=i.value.trim();if(t){routeChat(t);i.value=""}}}
function routeChat(t){state.chat.push({r:"user",t});const s=subjectFromText(t);let reply="Got it. I saved that to PLE-mate’s local memory.";if(/(done|finished|complete)/i.test(t)&&s){s.studied=s.hours||s.studied;s.completed=true;state.pet.careMessage=`Hikari celebrated ${s.name} with you. ✨`;reply=`Amazing, MD! I marked ${s.name} complete. ${s.hours?`Tracked workload: ${hrs(s.hours)}.`:""} Performance remains ${s.performance??"—"}% and was not changed.`;state.pet.xp+=80;state.pet.coins+=40}else if(/what should i study|study suggestion/i.test(t)){reply=advice()}else if(/studied\s+([0-9.]+)\s*(hours?|hrs?)/i.test(t)&&s){const n=+(t.match(/studied\s+([0-9.]+)\s*(hours?|hrs?)/i)||[])[1];s.studied=Math.min(s.hours,s.studied+n);reply=`Logged ${n}h for ${s.name}. Hikari earned study rewards from the progress change.`}state.chat.push({r:"bot",t:reply});save();updateProgressRewards();render()}
function subjectFromText(t){const x=t.toLowerCase();const map={microbio:"Microbiology",microbiology:"Microbiology",micro:"Microbiology",physio:"Physiology",physiology:"Physiology",patho:"Pathology",pathology:"Pathology",pharma:"Pharmacology",pharmacology:"Pharmacology",surg:"Surgery",surgery:"Surgery",obgyn:"OBGyn",biochem:"Biochemistry",biochemistry:"Biochemistry",pedia:"Pediatrics",pediatrics:"Pediatrics",legmed:"Legal Medicine",legalmedicine:"Legal Medicine",anat:"Anatomy",anatomy:"Anatomy",prevmed:"Preventive Medicine",medicine:"Internal Medicine",im:"Internal Medicine"};for(const k in map)if(x.includes(k))return state.subjects.find(s=>s.name===map[k]);return null}
function advice(){const p=getPicks()[0];return p?`Based on your current data, focus next on ${p.name}. Performance is ${p.performance??"—"}%, ${p.hours?hrs(p.hours-p.studied)+" remain tracked.":"workload is not entered."} Start with the highest-yield unfinished task, then use practice questions.`:"Add workload and deadline data first so I can rank your priorities."}
function setupPomo(){let choices=document.querySelectorAll("[data-pomo-length]");choices.forEach(b=>b.onclick=()=>{choices.forEach(x=>x.classList.remove("active"));b.classList.add("active");pomo.length=+b.dataset.pomoLength;pomo.sec=pomo.length*60;pomo.total=pomo.sec;document.getElementById("pomoStatus").textContent="Ready";document.getElementById("pomoMode").textContent=pomo.length===100?"Deep Focus":pomo.length===45?"Focus Session":"Focus Session";paintPomo()});document.getElementById("pomoStart").onclick=()=>{if(pomo.timer)return;pomo.timer=setInterval(()=>{pomo.sec--;paintPomo();if(pomo.sec<=0){clearInterval(pomo.timer);pomo.timer=null;const reward=pomo.length===100?{c:100,e:20,x:40}:{c:pomo.length===45?45:25,e:pomo.length===45?10:5,x:pomo.length===45?20:10};state.pet.coins+=reward.c;state.pet.energy=Math.min(100,state.pet.energy+reward.e);state.pet.xp+=reward.x;state.pet.careMessage=`Pomodoro complete! +${reward.c} coins and +${reward.e} Energy. ✨`;save();document.getElementById("pomoStatus").textContent="Complete ✨"}}},1000);document.getElementById("pomoStatus").textContent="Studying"};document.getElementById("pomoPause").onclick=()=>{clearInterval(pomo.timer);pomo.timer=null;document.getElementById("pomoStatus").textContent="Paused"};document.getElementById("pomoReset").onclick=()=>{clearInterval(pomo.timer);pomo.timer=null;pomo.sec=pomo.length*60;pomo.total=pomo.sec;document.getElementById("pomoStatus").textContent="Ready";paintPomo()};paintPomo()}
function paintPomo(){const t=document.getElementById("pomoTime");if(!t)return;const m=Math.floor(pomo.sec/60),s=pomo.sec%60;t.textContent=`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;const ring=document.getElementById("pomoRing");const pct=pomo.total?Math.max(0,pomo.sec/pomo.total):0;let color=pct<.15?"#e45b63":pct<.35?"#e4a82d":"#784ab0";ring.style.setProperty("--pomo-color",color);ring.style.setProperty("--pomo-pct",`${(1-pct)*100}%`);document.getElementById("pomoReward").textContent=`${pomo.length} min = ${pomo.length===100?"+100 coins · +20 energy":pomo.length===45?"+45 coins · +10 energy":"+25 coins · +5 energy"}`}
function petPage(){const st=stage(),dirty=visualState()<70;document.getElementById("petImage").src=stageImages[st];applyPetVisual(document.getElementById("petImage"),dirty);document.getElementById("petStageName").textContent=`Level ${st+1} · ${stageNames[st]}`;document.getElementById("petXp").textContent=`${state.pet.xp} / 500 XP`;document.getElementById("petXpBar").style.width=state.pet.xp/500*100+"%";document.getElementById("petEnergy").textContent=state.pet.energy;document.getElementById("petCoins").textContent=state.pet.coins;document.getElementById("petGems").textContent=state.pet.gems;document.getElementById("petCondition").textContent=dirty?stageCare[st].dirty:stageCare[st].clean;document.getElementById("petCareMessage").textContent=state.pet.careMessage;document.getElementById("nextStage").textContent=`Next evolution is driven mostly by study progress. Current progress: ${progressPct().toFixed(1)}%`;document.querySelectorAll("[data-pet-care]").forEach(b=>b.onclick=()=>doCare(b.dataset.petCare))}
function doCare(type){const costs={feed:{e:10,c:0,m:10,cl:8,msg:"Hikari happily ate her meal. 🍚"},pet:{e:5,c:0,m:12,cl:4,msg:"Hikari curled up and purred. 🐾"},shower:{e:15,c:0,m:8,cl:40,msg:"Hikari is sparkling clean. 💧✨"}};const x=costs[type];if(!x)return;if(state.pet.energy<x.e){state.pet.careMessage="Hikari is low on Energy. Study for another hour to refill her energy."}else{state.pet.energy-=x.e;state.pet.mood=Math.min(100,state.pet.mood+x.m);state.pet.cleanliness=Math.min(100,state.pet.cleanliness+x.cl);state.pet.careMessage=x.msg}save();render()}
function claimGift(){state.pet.coins+=25;state.pet.energy=Math.min(100,state.pet.energy+5);state.pet.careMessage="Gift claimed! Hikari looks a little happier. ✨";save();render()}
function petPageTemplate(){/* DOM comes from template */}
function oplanPage(){const p=getPicks();document.getElementById("oplanToday").innerHTML=p.map((s,i)=>`<div class="study-item"><b>${i+1}.</b><span>${subjectIcons[s.name]||"📘"} ${esc(s.name)}</span><span class="tag">${s.performance<30?"High Need":s.deadline?"Due Soon":"Priority"}</span></div>`).join("")||"<p>No workload/deadline data yet.";document.getElementById("oplanWeek").innerHTML=p.map(s=>`<div class="tip"><b>${esc(s.name)}</b><div class="muted">${s.deadline?"Deadline: "+new Date(s.deadline).toLocaleDateString()+" · ":""}${s.hours?hrs(s.hours-s.studied)+" remaining":"workload not entered"}</div><div>${esc(s.focus)}</div></div>`).join("");document.getElementById("tips").innerHTML=tips.map(t=>`<div class="tip">${t}</div>`).join("");document.getElementById("accountability").innerHTML=`<p><b>Tracked study:</b> ${hrs(totalStudied())}</p><p>Hikari's growth is driven primarily by real progress. Pomodoro sessions are bonus rewards, not the main evolution engine.</p>`}
function calendarPage(){const box=document.getElementById("calendarEmbed");box.innerHTML=state.calendarUrl?`<iframe src="${esc(state.calendarUrl)}" loading="lazy" title="Google Calendar"></iframe>`:"<div class='muted'>Add a Google Calendar embed URL in Settings.</div>";document.getElementById("calendarEvents").innerHTML=""}
function corkboardPage(){const b=document.getElementById("board");b.innerHTML=state.board.map((x,i)=>`<div class="board-item" data-i="${i}" style="left:${x.x}px;top:${x.y}px;width:${x.w}px;height:${x.h}px;background:${x.color}">${x.type==="image"?`<img src="${x.data}">`:`<textarea>${esc(x.text||"")}</textarea>`}</div>`).join("");document.querySelectorAll(".board-item").forEach(el=>{const i=+el.dataset.i,ta=el.querySelector("textarea");if(ta)ta.oninput=e=>{state.board[i].text=e.target.value;save()};let drag=false,ox=0,oy=0;el.onmousedown=e=>{if(e.target.tagName==="TEXTAREA"||e.target.tagName==="IMG")return;drag=true;ox=e.clientX-el.offsetLeft;oy=e.clientY-el.offsetTop};document.onmousemove=e=>{if(drag){el.style.left=Math.max(0,e.clientX-ox)+"px";el.style.top=Math.max(0,e.clientY-oy)+"px"}};document.onmouseup=()=>{if(drag){drag=false;state.board[i].x=el.offsetLeft;state.board[i].y=el.offsetTop;state.board[i].w=el.offsetWidth;state.board[i].h=el.offsetHeight;save()}}});document.getElementById("addNote").onclick=()=>{state.board.push({type:"note",text:"✨ Hikari: One more step, future MD.",x:40+state.board.length*15,y:40+state.board.length*15,w:230,h:150,color:"#fff3c8"});save();corkboardPage()};document.getElementById("boardImage").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{state.board.push({type:"image",data:r.result,x:70,y:70,w:260,h:190,color:"#fff"});save();corkboardPage()};r.readAsDataURL(f)}}
function openSubject(i){const modal=document.getElementById("modal");modal.classList.remove("hidden");const s=state.subjects[i];const days=s.deadline?Math.ceil((new Date(s.deadline)-new Date())/86400000):null;document.getElementById("modalBody").innerHTML=`<div class="subject-title"><span class="subject-icon big">${subjectIcons[s.name]||"📘"}</span><div><h1 style="color:${s.color}">${esc(s.name)}</h1><p>${esc(s.overview||"")}</p></div></div><div class="details"><div class="detail"><b>Performance</b>${s.performance??"—"}%</div><div class="detail"><b>Difficulty</b>${s.difficulty?s.difficulty+"/10":"Not entered"}</div><div class="detail"><b>Progress</b>${s.hours?Math.round(s.studied/s.hours*100)+"%":"Workload not entered"}</div><div class="detail"><b>Hours remaining</b>${s.hours?hrs(s.hours-s.studied):"—"}</div><div class="detail"><b>Deadline</b>${s.deadline?new Date(s.deadline).toLocaleString():"Not entered"}</div><div class="detail"><b>Days remaining</b>${days==null?"—":days<0?"Past due":days}</div></div><div class="mini-lore"><b>🎯 What you should focus on</b><p>${esc(s.focus)}</p></div><h3>📚 Known resources</h3><ul>${s.handout?`<li>Main handout: ${s.handout} pages</li>`:""}${s.lecture?`<li>Lecture workload: ${hrs(s.lecture/3600)}</li>`:""}${s.supertable?`<li>Micro Supertable: ${s.supertable} pages</li>`:""}${s.supersamplex?`<li>Supersamplex: ${s.supersamplex} items</li>`:""}<li>Practice tests: 5 sets planned</li></ul>`;document.getElementById("closeModal").onclick=()=>modal.classList.add("hidden")}
function subjectsPage(){document.getElementById("subjectCards").innerHTML=state.subjects.map((s,i)=>`<article class="subject-card" data-i="${i}" style="border-top:5px solid ${s.color}"><div class="subject-card-title"><span class="subject-icon">${subjectIcons[s.name]||"📘"}</span><h2>${esc(s.name)}</h2></div><div class="bar"><div style="width:${s.hours?Math.min(100,s.studied/s.hours*100):0}%;background:${s.color}"></div></div><div>${s.performance??"—"}% performance</div><div class="muted">Difficulty: ${s.difficulty?s.difficulty+"/10":"not entered"}</div><div class="muted">${s.hours?hrs(s.hours-s.studied)+" remaining":"workload not entered"}</div></article>`).join("");document.querySelectorAll(".subject-card").forEach(c=>c.onclick=()=>openSubject(+c.dataset.i));document.getElementById("addSubject").onclick=()=>{const n=prompt("Subject name");if(n&&!state.subjects.some(s=>s.name.toLowerCase()===n.toLowerCase())){state.subjects.push({name:n,color:"#8d6bb8",performance:null,hours:0,studied:0,difficulty:null,focus:"Add workload and strategy.",overview:"New subject",deadline:""});save();subjectsPage()}}}
function settingsPage(){document.getElementById("pleDateInput").value=state.pleDate;document.getElementById("pleDateInput").onchange=e=>{state.pleDate=e.target.value;save()};document.getElementById("calendarUrl").value=state.calendarUrl;document.getElementById("saveCalendar").onclick=()=>{state.calendarUrl=document.getElementById("calendarUrl").value.trim();save();alert("Calendar URL saved locally.")};document.getElementById("exportData").onclick=()=>{const a=document.createElement("a"),b=new Blob([JSON.stringify(state,null,2)],{type:"application/json"});a.href=URL.createObjectURL(b);a.download="ple-mate-backup.json";a.click()};document.getElementById("importData").onchange=async e=>{try{state={...state,...JSON.parse(await e.target.files[0].text())};save();alert("Backup imported.");settingsPage()}catch{alert("Invalid backup.")}};document.getElementById("clearData").onclick=()=>{if(confirm("Clear all PLE-mate data stored in this browser?")){localStorage.removeItem(KEY);state=load();page="dashboard";render()}}}
function init(){render()}init();
